prometheus_postgres_dbname: "{{ postgres.database_name }}"
prometheus_port: 9090
prometheus_web_listen_address: "0.0.0.0:{{ prometheus_port }}"
node_exporter_port: 9100
node_exporter_web_listen_address: "0.0.0.0:{{ node_exporter_port }}"
prometheus_postgres_port: 9187
redis_exporter_port: 9121

prometheus_targets:
  node:
    - targets: "{{ groups.all | map('regex_replace', '^(.*)$', '\\1:' ~ node_exporter_port) | list }}"
  postgres:
    - targets: "{{ groups.postgres | map('regex_replace', '^(.*)$', '\\1:' ~ prometheus_postgres_port) | list }}"
  redis:
    - targets: "{{ groups.redis | map('regex_replace', '^(.*)$', '\\1:' ~ redis_exporter_port) | list }}"

prometheus_scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - "{{ inventory_hostname }}:{{ prometheus_port }}"
  - job_name: node
    file_sd_configs:
    - files:
      - "{{ prometheus_config_dir }}/file_sd/node.yml"
  - job_name: postgres
    file_sd_configs:
    - files:
      - "{{ prometheus_config_dir }}/file_sd/postgres.yml"
  - job_name: redis
    file_sd_configs:
    - files:
      - "{{ prometheus_config_dir }}/file_sd/redis.yml"

grafana_security:
  admin_user: admin
  admin_password: admin
grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: "http://{{ groups.prometheus.0 }}:{{ prometheus_port }}"
grafana_dashboards:
  - dashboard_id: 11074
    revision_id: 2
    datasource: "{{ grafana_datasources.0.name }}"
  - dashboard_id: 6742
    revision_id: 1
    datasource: "{{ grafana_datasources.0.name }}"
  - dashboard_id: 763
    revision_id: 1
    datasource: "{{ grafana_datasources.0.name }}"
