prometheus_port: 9090
prometheus_web_listen_address: "0.0.0.0:{{ prometheus_port }}"

prometheus_targets:
  node:
    - targets: "{{ groups.all | map('regex_replace', '^(.*)$', '\\1:9100') | list }}"
  postgres:
    - targets: "{{ groups.postgres | map('regex_replace', '^(.*)$', '\\1:9187') | list }}"
  redis:
    - targets: "{{ groups.redis | map('regex_replace', '^(.*)$', '\\1:9121') | list }}"
  load_balancing:
    - targets: "{{ groups.load_balancing | map('regex_replace', '^(.*)$', '\\1:9101') | list }}"

prometheus_scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - "{{ inventory_hostname }}:{{ prometheus_port }}"
  - job_name: node
    file_sd_configs:
    - files:
      - "{{ prometheus_config_dir }}/file_sd/node.yml"
  - job_name: postgres
    file_sd_configs:
    - files:
      - "{{ prometheus_config_dir }}/file_sd/postgres.yml"
  - job_name: redis
    file_sd_configs:
    - files:
      - "{{ prometheus_config_dir }}/file_sd/redis.yml"
  - job_name: load balancing
    file_sd_configs:
    - files:
      - "{{ prometheus_config_dir }}/file_sd/load_balancing.yml"

grafana_security:
  admin_user: admin
  admin_password: admin
grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: "http://{{ groups.prometheus.0 }}:{{ prometheus_port }}"
grafana_dashboards:
  - dashboard_id: 11074 # Node exporter
    revision_id: 2
    datasource: "{{ grafana_datasources.0.name }}"
  - dashboard_id: 6742 # Postgres
    revision_id: 1
    datasource: "{{ grafana_datasources.0.name }}"
  - dashboard_id: 763 # Redis
    revision_id: 1
    datasource: "{{ grafana_datasources.0.name }}"
  - dashboard_id: 2428 # HAProxy
    revision_id: 1
    datasource: "{{ grafana_datasources.0.name }}"
