---
postgresql_locale: "en_US.UTF-8"

postgresql_user:
  name: "simple-server"

postgresql_database_name: "{{ deploy_env }}-{{ app_name }}-db"

postgresql_pg_hba:
  - {contype: local, databases: all, users: postgres, method: peer}
  - {contype: host, databases: all, users: all, source: '0.0.0.0', method: md5}
  - {contype: host, databases: all, users: all, source: '::/0', method: md5}

__postgresql_data_dir: "/var/lib/postgresql/{{ __postgresql_version }}/main"
__postgresql_bin_path: "/usr/lib/postgresql/{{ __postgresql_version }}/bin"
__postgresql_config_path: "/etc/postgresql/{{ __postgresql_version }}/main"

