---
- name: create logs directory on storage
  file:
    path: "{{ rsync_destination_dir }}"
    state: directory
  become: yes
  become_user: "{{ deploy_user }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups.storage }}"

- name: set up logrotate
  template:
    src: "etc/logrotate.d/config.j2"
    dest: "{{ logrotate_config_file }}"
    owner: root
  become: yes
