---
- name: copy sidekiq monit file
  template:
    src: etc/monit/conf-available/sidekiq.monitrc
    dest: /etc/monit/conf-available/sidekiq.monitrc
  become: true
  notify: restart monit

- name: enable monit for sidekiq
  file: >
    state=link
    src=/etc/monit/conf-available/sidekiq.monitrc
    dest=/etc/monit/conf-enabled/sidekiq.monitrc
  become: true
  notify: restart monit

- name: reload monit
  service: name=monit state=reloaded
  become: yes

- name: restart sidekiq
  shell: monit restart "{{ sidekiq_service_name }}"
  tags: restart-sidekiq
  become: true
  ignore_errors: yes
