---
alertmanager_template_files: "roles/monitoring/files/alertmanager/templates/*.tmpl"
alertmanager_receivers:
  - name: email
    email_configs:
      - to: 'alerts@simple.org'
        from: 'standalone-alerts@simple.org'
        smarthost: 'smtp.sendgrid.net:587'
        auth_username: "{{ server.config.sendgrid_username }}"
        auth_password: "{{ server.config.sendgrid_password }}"
        html: '{% raw %}{{ template "email" . }}{% endraw %}'

alertmanager_route:
  receiver: "email"
  routes:
    - match:
        severity: critical
      receiver: email
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 5m
