# simple server tasks
---
- name: Deploy | Include secrets
  include_vars:
    file: "{{ secrets_file }}"
    name: secrets

- name: Deploy | Create apps directory
  file:
    path: /home/deploy/apps/{{app_name}}/shared
    state: directory
    owner: "{{ deploy_user }}"

- name: Deploy | Copy .env template file
  template:
    src: .env.j2 
    dest: /home/deploy/apps/{{app_name}}/shared/.env.production
