---
- name: Define postgresql version
  set_fact:
    postgresql_version: "10"
  when: postgresql_version is not defined

- name: Define postgresql_daemon.
  set_fact:
    postgresql_daemon: "postgresql@{{ postgresql_version }}-main"
  when: postgresql_daemon is not defined

- name: ensure apt-transport-https is installed
  apt: name=apt-transport-https state=present
  become: true

- name: add postgresql apt key
  apt_key:
    url:  https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: true

- name: add postgresql repositories
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main"
    state: present
  register: postgres_repo
  become: true

- name: update apt cache if repo was added
  apt: update_cache=yes
  when: postgres_repo.changed
  become: true

- name: Ensure PostgreSQL 10 packages are installed.
  apt:
    pkg:
      - postgresql-10
      - postgresql-contrib
      - libpq-dev
      - python-ipaddress
      - python-psycopg2
    state: present

- name: Ensure all configured locales are present.
  locale_gen:
    name: "{{ postgresql_locale }}"
    state: present
  register: locale_gen_result

- name: Force-restart PostgreSQL after new locales are generated.
  service:
    name: "{{ postgresql_daemon }}"
    state: restarted
  when: locale_gen_result.changed

- name: Grant the default permisions for pg_hba conf.
  with_items: "{{ postgresql_pg_hba }}"
  postgresql_pg_hba:
    dest: "/var/lib/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    contype: "{{ item.contype }}"
    users: "{{ item.users }}"
    source: "{{ item.source | default('::1') }}"
    databases: "{{ item.databases }}"
    method: "{{ item.method }}"
    create: true

- name: Create Postgresql database
  postgresql_db:
    name: "{{ postgresql_database_name }}"
  become: yes
  become_user: postgres

# TODO: Read password from vault
- name: Create Postgresql user
  postgresql_user:
    name: "{{ postgresql_user.name }}"
    password: "{{ postgresql_user.password }}"
    db: "{{ postgresql_database_name }}"
    encrypted: true
    priv: ALL
  become: true
  become_user: postgres

- name: Allow postgres to accept all connections
  postgresql_set:
    name: listen_addresses
    value: "*"
  register: postgres_listen_addresses
  become: true
  become_user: postgres

- name: Restart postgresql after updating listen addresses
  service:
    name: "{{ postgresql_daemon }}"
    state: restarted
  when: postgres_listen_addresses.changed
