---
- name: ensure apt-transport-https is installed
  apt: name=apt-transport-https state=present
  become: true

- name: add postgresql apt key
  apt_key:
    url:  https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: true

- name: add postgresql repositories
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main"
    state: present
  register: postgres_repo
  become: true

- name: update apt cache if repo was added
  apt: update_cache=yes
  when: postgres_repo.changed
  become: true

- name: Ensure PostgreSQL 10 packages are installed.
  apt:
    pkg:
      - postgresql-10
      - postgresql-contrib
      - libpq-dev
      - python-ipaddress
      - python-psycopg2
    state: present

- name: Ensure all configured locales are present.
  locale_gen:
    name: "{{ postgresql_locale }}"
    state: present
  register: locale_gen_result

- name: Force-restart PostgreSQL after new locales are generated.
  service:
    name: "{{ postgresql_daemon }}"
    state: restarted
  when: locale_gen_result.changed

- name: Grant the default permisions for pg_hba conf.
  with_items: "{{ postgresql_pg_hba }}"
  postgresql_pg_hba:
    dest: "/var/lib/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    contype: "{{ item.contype }}"
    users: "{{ item.users }}"
    source: "{{ item.source | default('::1') }}"
    databases: "{{ item.databases }}"
    method: "{{ item.method }}"
    create: true
