# load balancing tasks
---
- name: Load Balancing | Install HAProxy
  apt: 
    pkg: "haproxy={{ haproxy_version }}"
    update_cache: yes
  become: true

- name: Load Balancing | Enable init script
  replace:
    dest: '/etc/default/haproxy' 
    regexp: 'ENABLED=0'
    replace: 'ENABLED=1'

- name: Load Balancing | Update HAProxy config
  template: 
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg 
    backup: yes
  notify: restart haproxy
