---
- name: Setup Prometheus
  hosts: monitoring
  roles:
    - cloudalchemy.prometheus
    
- name: Setup Grafana
  hosts: monitoring
  roles:
    - cloudalchemy.grafana
    
- name: Setup node exporter for all nodes
  hosts: all
  roles:
    - cloudalchemy.node-exporter

- name: allow all access to prometheus
  ufw:
    rule: allow
    port: "{{ prometheus_port }}"

name: allow all access to grafana
  ufw:
    rule: allow
    port: "{{ grafana_port }}"
    proto: tcp
