---
- name: setup node exporter for all nodes
  hosts: all
  roles:
    - monitoring
    - cloudalchemy.node-exporter

- name: setup postgres exporter
  hosts: postgres
  roles:
    - monitoring
    - ome.prometheus_postgres

- name: setup redis exporter
  hosts: redis
  roles:
    - monitoring
    - prometheus_redis_exporter
  become: true

- name: setup HAProxy exporter
  hosts: load_balancing
  roles:
    - monitoring
    - bdellegrazie.haproxy_exporter

- name: setup nginx exporter
  hosts: webservers
  roles:
    - monitoring
    - bdellegrazie.nginx_exporter

- name: setup Prometheus and Alertmanager
  hosts: prometheus
  vars_files:
    - "roles/simple-server/vars/{{ deploy_env }}/secrets.yml"
  roles:
    - monitoring
    - cloudalchemy.prometheus
    - cloudalchemy.alertmanager

- name: setup Grafana
  hosts: grafana
  roles:
    - monitoring
    - cloudalchemy.grafana

- name: allow monitoring ports through firewall
  hosts: monitoring
  become: true
  tasks:
  - name: allow all access to prometheus
    ufw:
      rule: allow
      port: "{{ prometheus_port }}"

  - name: allow all access to grafana
    ufw:
      rule: allow
      port: "{{ grafana_port }}"
