---
- src: ansistrano.deploy
- src: ansistrano.rollback
- src: cloudalchemy.prometheus
- src: cloudalchemy.grafana
- src: cloudalchemy.node-exporter
- src: davidwittman.redis
- src: ome.prometheus_postgres
- src: http://github.com/idealista/prometheus_redis_exporter_role.git
  scm: git
  version: 2.0.0
  name: prometheus_redis_exporter
- src: bdellegrazie.haproxy_exporter
